name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean package

      # Build Docker image
      - name: Build Docker image
        run: docker build -t livelo-app .

      # Push Docker image to Docker Hub (optional)
      # Replace 'your-docker-username' with your Docker Hub username
      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: |
          docker tag livelo-app ${{ secrets.DOCKER_USERNAME }}/livelo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/livelo-app:latest

      # Deploy Docker image using Docker Compose
      - name: Deploy with Docker Compose
        run: docker-compose up -d

